version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run:
          name: Installing GCC, git and cmake
          command: |
              apt-get update 
              apt-get install -yqq --no-install-recommends software-properties-common \
                 git cmake gcc g++ curl libunbound-dev libunwind8-dev libcurl4-openssl-dev \
                 libhidapi-dev \
                 libssl-dev libsodium-dev libzmq3-dev pkg-config libpgm-dev \
                 libboost-program-options-dev libboost-chrono-dev libboost-filesystem-dev \
                 libboost-serialization-dev libboost-regex-dev  libboost-locale-dev \
                 libboost-thread-dev libboost-fiber-dev \
                 libjsoncpp-dev uuid-dev libmysql++-dev 
      - checkout
      - run:
          name: Get Last worktips commit hash 
          command: |
              export WORKTIPS_COMMIT=`git ls-remote https://github.com/worktips-project/worktips HEAD | head -n1 | awk '{print $1;}'`
              echo $WORKTIPS_COMMIT > ~/worktipscommit
              cat ~/worktipscommit
      - restore_cache:
          key: v01-worktips-{{ checksum "~/worktipscommit" }}
      - run:
          name: Compile Worktips
          command: |
                  if [ ! -d "worktips" ]; then 
                  git clone --recurse-submodules https://github.com/worktips-project/worktips.git 
                  cd worktips
                  mkdir -p build/release && cd build/release
                  cmake -D CMAKE_BUILD_TYPE=Release ../..
                  cmake --build . --target cryptonote_core -- -j 2
                  cd ../..
                  fi
      - save_cache: 
          key: v01-worktips-{{ checksum "~/worktipscommit" }}
          paths: 
            - "worktips"
      - run:
          name: Get submodules
          command: |
              git submodule update --init --recursive
      - run:
          name: Creating Build Files 
          command: 'cmake -DWORKTIPS_DIR=/root/project/worktips -DBUILD_TESTS=ON -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build -- -j 2'
