#ifndef OM_LOG_H
#define OM_LOG_H

#define OPENWORKTIPS_LOG_CATEGORY "OM"

#define OMINFO  CLOG(INFO, OPENWORKTIPS_LOG_CATEGORY)
#define OMWARN  CLOG(WARNING, OPENWORKTIPS_LOG_CATEGORY)
#define OMERROR CLOG(ERROR, OPENWORKTIPS_LOG_CATEGORY)

//#define OMVLOG1  CVLOG(1, OPENWORKTIPS_LOG_CATEGORY)
//#define OMVLOG2  CVLOG(2, OPENWORKTIPS_LOG_CATEGORY)
//#define OMVLOG3  CVLOG(3, OPENWORKTIPS_LOG_CATEGORY)
//#define OMVLOG4  CVLOG(4, OPENWORKTIPS_LOG_CATEGORY)

#define OMVLOG1  CLOG(INFO, OPENWORKTIPS_LOG_CATEGORY)
#define OMVLOG2  CLOG(INFO, OPENWORKTIPS_LOG_CATEGORY)
#define OMVLOG3  CLOG(INFO, OPENWORKTIPS_LOG_CATEGORY)
#define OMVLOG4  CLOG(INFO, OPENWORKTIPS_LOG_CATEGORY)

#define OMINFO_IF(cond)  CLOG_IF(cond, INFO, OPENWORKTIPS_LOG_CATEGORY)
#define OMWARN_IF(cond)  CLOG_IF(cond, WARNING, OPENWORKTIPS_LOG_CATEGORY)
#define OMERROR_IF(cond) CLOG_IF(cond, ERROR, OPENWORKTIPS_LOG_CATEGORY)


#endif // OM_LOG_H  
